### PR TITLE
Support for Python 3.9 (and drop Python < 3.5)

### PR DESCRIPTION
**Pull request by daniele-athome**
I'm not really sure about string_escape replacement, but I couldn't do anything better than that. If you have ideas you're welcome to change it.

### CODE REVIEW

**Comment by rbarrois** [comment]
Hi! And thanks for the pull request, it's greatly appreciated :)

I've had to check a bit to remember what `string_replace` was used for; it's basically to allowing defining the "end line separator" manually to `\r`, `\n` and friends.

I'm going to fix that part (it's not documented, which is a problem), which should make your branch much easier to merge!

**Comment by rbarrois** [comment]
And there we go! The new code should remove the need for those weird escapes — and provide improved documentation!

**Comment by daniele-athome** [comment]
Thanks! I've rebased my code.

**Comment by m040601** [comment]
Good to know this project is not abandoned, apparently.

A very useful thing especially for Music Player daemo. I'm evaluating it and comparing it to other solutions.

1. Could you please  confirm that you still plan on maintaining this project ?

I had an issue opened without response here, https://github.com/rbarrois/inputexec/issues/10


2. Since the last commits, appart from the one's today, were from 3 years ago, could you please release a new version, on https://github.com/rbarrois/inputexec/releases ?

Thanks in advance

**Comment by rbarrois** [comment]
@m040601 I'm using it for MPD, so I do intend to keep it running; I don't think new features are needed however.
Once it's successfully updated for newer Python versions, I'll make a full release ;)

**Comment by rbarrois** [comment]
Thanks again for the contribution!
I've just released version 0.2.5 which contains most of these fixes; however, I've opted to keep Python2 support around for now, it's not costly to have and might be useful to some projects using this application in hard-to-upgrade systems!

**Pull request closed without merging**
